pesh_portfolio_index:
    path:     /
    defaults: { _controller: PeshPortfolioBundle:Portfolio:index }

pesh_portfolio_about:
    path:     /about
    defaults: { _controller: PeshPortfolioBundle:Portfolio:about }

pesh_portfolio_cv:
    path:     /cv
    defaults: { _controller: PeshPortfolioBundle:Portfolio:cv }

pesh_portfolio_homepage:
    path:     /veille
    defaults: { _controller: PeshPortfolioBundle:Portfolio:veille }

pesh_portfolio_homepage:
    path:     /contact
    defaults: { _controller: PeshPortfolioBundle:Portfolio:contact }
