pesh_portfolio_index:
    path:     /
    defaults: { _controller: PeshPortfolioBundle:Portfolio:index }

pesh_portfolio_travaux:
    path:     /travaux
    defaults: { _controller: PeshPortfolioBundle:Portfolio:travaux }

pesh_portfolio_cv:
    path:     /cv
    defaults: { _controller: PeshPortfolioBundle:Portfolio:cv }

pesh_portfolio_veille:
    path:     /veille
    defaults: { _controller: PeshPortfolioBundle:Portfolio:veille }

pesh_portfolio_contact:
    path:     /contact
    defaults: { _controller: PeshPortfolioBundle:Portfolio:contact }

pesh_portfolio_ajaxproxy:
    path:     /ajaxproxy/{url}
    defaults: { _controller: PeshPortfolioBundle:Portfolio:ajaxproxy, url: null}
